language: cpp
compiler:
   - gcc
   - clang
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DjpT7TcFeS7XcnkDEuEo4zkvTD4dlTMPcWVJ45qIUpOsNLvkERb+BcxEMJe2TSfdIPi6zkSGr1Do3nR3Oq6OqTNq0yrfS0G0ay1bv1/F5L9T2rYGZPOlCG1jFvcRjN90gAE4hUDE2kBjaFC/Rt/YiYvtgl0gr4lz+zh2QH2x5cU="


before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "rsijiao0518/vampire-coverity"
      description: "Vampire"
    notification_email: 490436312@qq.com
    build_command_prepend: "./configure"
    build_command: "make -j2"
    branch_pattern: master
